### ISSUE TITLE
A few issues with 'defaults'.

### ISSUE THREAD

**Issue by kblanks** [Cubition/AuthServer#1]
https://github.com/Cubition/AuthServer/blob/master/config.php

You should either pass in the options as environment variables (best option IMO) or have a template configuration that users copy in to the correct location.

https://github.com/Cubition/AuthServer/blob/master/database.sql#L10

Why is that a default? Different database engines may be used, don't just set the default to the engine you're running the application on.

https://github.com/Cubition/AuthServer/blob/master/register.php#L23

What is the purpose of the `$2y$10$` string? If it's a secret used when hashing the passwords, surely it would be a configuration option?

**Comment by Xesau** [comment]
First of all, thank you for looking around in my code :)

1. It's an SQL-dump. If you are not sattisfied, change it.

2. That's the prefix for blowfish hashing, so PHP understands how he should hash the passwords. I chose this because it is an industry standard. For this applies the same: change it if you want to.

If the entire system doesn't fit for you, consider creating an entire new project.  The API is really simple, and it's even explained in one of recenter commits.

PS: The reason this code is here is not because you will EVER need it, but just to show how the back-end of the Cubition Auth server works.

**Comment by kblanks** [comment]
> That's the prefix for blowfish hashing, so PHP understands how he should hash the passwords. I chose this because it is an industry standard. For this applies the same: change it if you want to.

Ah, I didn't know this since I don't PHP.

What about the first question?

**Comment by Xesau** [comment]
> What about the first issue?
It's no issue. 
> PS: The reason this code is here is not because you will EVER need it, but just to show how the back-end of the Cubition Auth server works.

**Comment by kblanks** [comment]
;-;
